### ISSUE TITLE
Write a parser to handle percentages

### ISSUE THREAD

**Issue by mikkoh** [Jam3/f1-dom#7]
It would be nice if you could do something like.

``` javascript
from: 
  left: "10%"

to:
  left: "50%"
```

Where F1 could animate these values.

Also a similar case would be to handle `translate: [ '-50%', 0, 0]`. Although this may not be possible as the translate array gets calculated into a transformation matrix and therefore we'd need to know the calculated size of the element we're animating.

**Comment by andrevenancio** [comment]
any news on this feature?

**Comment by mikkoh** [comment]
It's something I'd like to look at this week depending on how much other stuff comes up.

I think one thing that's tough is lets say you're using percentages and then you switch in another state to not use percentages it will cause issues.

I'm not sure how browsers handle that case when using CSS transitions.

**Comment by andrevenancio** [comment]
Is this implemented?

**Comment by njam3** [comment]
@andrevenancio Yup! sorry, should have mentioned it. It was added to the f1 library as of version 8.0.0  I have not updated the dependencies in f1-dom yet though, I will do so soon.
